### ISSUE TITLE
Production build hangs

### ISSUE THREAD

**Issue by vuhrmeister** [jaredpalmer/razzle#1035]
The build hangs, it never stops. That's the output:

```shell
> razzle build

Creating an optimized production build...
Compiling client...
Compiled client successfully.
Compiling server...
Compiled server successfully.
Compiled successfully.

File sizes after gzip:

  65.76 KB  build/static/js/bundle.8241e039.js
```

After that nothing happens anymore, I need to cancel the process.

Obviously the build succeeded but it does not actually quit the process.

I'm on version 3.0.0 with no custom configuration or plugins.

**Comment by vuhrmeister** [comment]
I just tried to locate the issue. Obviously it's an issue with tree shaking. I'm using Material-UI and import my components like so:

```javascript
import { CssBaseline } from '@material-ui/core'
```

But if I import them by path, then the build runs just fine:

```javascript
import CssBaseline from '@material-ui/core/CssBaseline'
````

Unfortunately there is no error output.

Running the app in development mode works just fine, no matter the import style!

**Comment by vuhrmeister** [comment]
Also there are circumstances where the build output stops even earlier:

```shell
> razzle build

Creating an optimized production build...
Compiling client...
Compiled client successfully.
Compiling server...
```

I have a component like:

```javascript
const Footer = () => (
  <footer>
    <Component1 />
    <Component2 />
  </footer>
)
```

If I either remove `<Component1 />` or `<Component2 />` the process runs further until hanging after displaying the file size (like described above).

**Comment by vuhrmeister** [comment]
I checked out the Material-UI example and fixed it so that it's working again. Here's the PR: https://github.com/jaredpalmer/razzle/pull/1041

And here is a version that breaks the build as described above: https://github.com/vuhrmeister/razzle/compare/fix-material-ui-example...material-ui-broken-build
I only changed the import statement.

Unfortunately this is the easiest case. In my (larger) application it breaks builds also with the (in the example) working import. There must be something else, but probably related to this one.

**Comment by gugaevkirill** [comment]
I have the same issue and I've noticed, that adding semicolon after import fixes the issue:
`import { CssBaseline } from '@material-ui/core'`

**Comment by gugaevkirill** [comment]
I've got the same Issue:
This import hangs production build:
```
import {ConnectedRouter} from 'connected-react-router';
```

But if I add another unused import after it, it will work:
```
import {ConnectedRouter} from 'connected-react-router';
import BrowserRouter from 'react-router-dom/BrowserRouter';
```

**Comment by artkravchenko** [comment]
@vuhrmeister, @gugaevkirill,

I've encounted this issue too. Thank you for investigating and pointing this out, you've helped me a lot.

In my case, `razzle build` hanged at the first time when I imported from ES modules friendly `@fluent/bundle` npm package:

```javascript
import { FluentBundle, FluentResource } from '@fluent/bundle';
```

However, after I've fixed this import declaration (by editing its source to `'@fluent/bundle/compat'`), I've got the same build hanging caused by

```javascript
import React from 'react';
```

inside one of the modules. I've fixed this one by rewriting it to

```javascript
const React = require('react');
```

Although the same module contained other import declarations from ES modules friendly packages such as `clsx`, they didn't cause the hang. I also had `react` import declarations in a lot of places too, but they worked well.

Later I've got another one randomly and decided to disable Webpack's processing of ES modules by editing the project's root `.babelrc` for some period of time:

```json
{
  "presets": [
    "razzle/babel",
    ["@babel/preset-env", { "modules": "commonjs" }]
  ]
}
```

This finally fixed the issue for me. I'm going to revisit this soon either to fix the bug's origin inside `razzle` or to migrate to another `razzle`-like solution.

(In fact, I'm currently on the way of creating the one with an eye on performance and other production aspects by myself. Just need some time to publish few more business oriented tools first.)

**Comment by trys** [comment]
@artkravchenko I've had the same issue, seems super inconsistent with the `require('react')` 'fix'.

What Node version are you rocking? I'm finding Node 11 compiles fine, but as soon as I use anything 12.x.x it hangs.

**Comment by artkravchenko** [comment]
> What Node version are you rocking?

@trys, I use 12.3.1. Just tested with 11.5.0 — confirm it doesn't hang there.

Surprisingly, if I have at least one dynamic import (`import('./path')`) processed with Webpack, the build doesn't hang even with Node 12.3.1.

**Comment by fivethreeo** [comment]
If this is still a issue reopen this
