### ISSUE TITLE
Incorrect port shown in terminal

### ISSUE THREAD

**Issue by theiliad** [jaredpalmer/razzle#1118]
Hi,
I'm seeing this message in Terminal:
![image](https://user-images.githubusercontent.com/14989804/66409489-a7377b80-e9be-11e9-9248-2b3c136fe4fe.png)

however, the client is running on port `3000`, which should be pointed out somewhere.

So nothing really breaking 👍Just need more clarification there

**Comment by klarstrup** [comment]
The actual port is designated in userland, typically in your src/index.js file. It's not actually something done on the razzle side of things.

But I do agree that the webpack-dev-server message is misleading, I don't know if there's a way to hide that specific message.

**Comment by laurencefass** [comment]
im having similar issues and i cant load assets because the client is trying to load them from port 3001.

**Comment by albertogasparin** [comment]
It would be great to have this better explained, at least. Spent a couple of hours trying to understand why my express routes where all returning 404, only to later realising that was looking at the wrong address. 
Can we potentially fix this by using webpack dev server proxy option? So we could have just one port to hit instead of 3000 for the server and 3001 for the assets.

**Comment by sydoluciani** [comment]
The source of confusion is "webpack-dev-server" log:
https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/status.js#L25

As soon as "webpack-dev-server" starts, those log messages will be printed in console, even with use of proxy.

There is a TODO, to disable the log:
https://github.com/webpack/webpack-dev-server/blob/master/lib/utils/status.js#L7

There is stats option that can be placed in webpack.config.js to disable the logging but that won't override the above logging even in a simple "webpack-dev-server" outside of Razzle.

This issue is related to "webpack-dev-server" and can be closed.

**Comment by fivethreeo** [comment]
Fixed, closing
