### ISSUE TITLE
support question: do i need to implement <StaticRouter> wrapper for a Razzle app?

### ISSUE THREAD

**Issue by laurencefass** [jaredpalmer/razzle#1141]
Im reading about server side rendering here: https://reacttraining.com/react-router/web/guides/server-rendering

The default create-razzle-app is a SSR app which contains a BrowserRouter not a StaticRouter.

Is there any explanation for requirement or need for  a StaticRouter in a Razzle App or can we just ignore it as Razzle provides its own implementation?

thanks

**Comment by anz000** [comment]
The server uses `StaticRouter` and the client uses `BrowserRouter`. The default samplea-pp uses it already. In my case, I has issue with `BrowserRouter`. The client would not route properly, the url would change but the content won't change. I used `Router` instead and it works great for me. It might have to do with some of my configurations within my application, but since it worked I didn't investigate any further.

**Comment by laurencefass** [comment]
many thanks.
