### ISSUE TITLE
localStorage on server.js???

### ISSUE THREAD

**Issue by itsemirhanengin** [jaredpalmer/razzle#1168]
Hello! I have a bullshit question.

I setted up GraphQL to my razzle app. Everything is running fine, i can see my graphql state at the bottom. Buuuut, i have to access localStorage object on my server.js file. Because, i have to store my user data from server.js on bottom window object.

Is it possible? Or maybe you can give me another idea for this problem. Thanks from now :)

**Comment by mAAdhaTTah** [comment]
You can't access localStorage on the server. Defer any access of localStorage to client-only (e.g. `useEffect` or `componentDidMount`).

**Comment by itsemirhanengin** [comment]
Don't I have a chance to do this... Because my initial state returns always user null... Or maybe i should not use HOC component? Is redux would work? What do you think?

**Comment by mAAdhaTTah** [comment]
How you hydrate from localStorage is dependent upon your app architecture & user needs. I can't answer that for you.

**Comment by itsemirhanengin** [comment]
I have to send my localStorage item to backend every request. That's why i need it.

**Comment by elliottjro** [comment]
This is a type of question that belongs more on StackOverflow and not really Razzle specific

**Comment by itsemirhanengin** [comment]
I know... But i couldn't find any solution for it :(

**Comment by filipecosta01** [comment]
Hey bud, use cookies instead of localStorage. With cookies and http-only configuration, you can setup everything you want for your user authentication in safer way and server-read only, avoiding XSS vulnerability.
On your server you set the cookie and reading from it gives you the ability to know when the user is authenticated or not according to your logic -token or whatever you are using.

**Comment by itsemirhanengin** [comment]
@filipecosta01 Thank you so much ^^ i tried it and it really worked! I'm really appreciate it :)
