### ISSUE TITLE
Update dependency for razzle-plugin-scss

### ISSUE THREAD

**Issue by gbrlsnchs** [jaredpalmer/razzle#1188]
Bump `node-sass-chokidar` to latest version in order to also bump its `node-sass` dependency version.

The current version is using `node-sass` version 4.11.0, which can't be downloaded on Linux.

**Comment by nimaa77** [comment]
oops, for now, we can't do that because the new version of these packages dropped support for nodejs < 8 and as razzle 3 minimum nodejs version is 8

but we are going to do upgrades very soon in razzle v4 

what you can do now is to copy `razzle-plugin-scss` source code to `razzle.config.js` file and configure it with the latest version of the dependencies
