### ISSUE TITLE
Better logging

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#268]
Really want improve logging. Seems like it is inevitable that we drop `react-dev-utils/formatWebpackMessages` and use a custom formatter. This would allow us to have one call to 

```js
const multiCompilers = compile([serverConfig, clientConfig])
```
 
In multi-compiler mode, we can still pass the respective `clientCompiler` to `webpack-dev-server` and watch the `serverCompiler` in pretty much the same way. However, we would then be able to write truly universal logger (which would look a lot like `formatWebpackMessages`, but handle multiple configs).

**Comment by jaredpalmer** [comment]
Going to post some screenshots of my ideas.

**Comment by jaredpalmer** [comment]
Razzle Loading/Compiling ... (probably powered by Ora)

![razzle_loading_cli](https://cloud.githubusercontent.com/assets/4060187/26683753/dca667ba-46b2-11e7-94bc-9f17a564a0b8.png)

Razzle Errors pipe below:
![razzle_error_cli](https://cloud.githubusercontent.com/assets/4060187/26683754/dca8c10e-46b2-11e7-8951-b6e8fbf5a0ff.png)

**Comment by jariz** [comment]
@jaredpalmer Did you already start on this?
Sounds like a fun issue to tackle!

**Comment by jaredpalmer** [comment]
Nope. Go for it!

I was talking to Sean Larkin at React Rally about Webpack and unfortunately there is literally zero way to tell if the errors are identical or not. So despite the current logger, we really should be showing both at all times.

**Comment by jariz** [comment]
hey @jaredpalmer, I think my PR was a bit too crazy and unstable regarding the UI side of things, but I still really liked the multicompiler approach and the general direction it was going.  
It made for a single compiler rather than 2 instances (more clear codebase and probably better for performance) and it would also show an error overlay when a server side compile would fail, which - I thought - was really cool.

Also the UI side of things could be toned down a bit with a less intrusive approach like just clearing the console whenever the server/client bundle becomes invalid, rather than having them display at all times like my PR had.

Let me hear what you think!

**Comment by jaredpalmer** [comment]
I’d be open to exploring it. How does multicompiler deal with the making the hashed names client assets available to the server? Is there a plug-in?

**Comment by jariz** [comment]
It 'solves' it be concatting the hashes together. I modified the webpack client to only grab the first part because it would attempt to accept server side HMR's otherwise.
