### ISSUE TITLE
Infinite recompile bug

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#302]
Will try to record a GIF if i stumbled upon this again.

**Comment by thangngoc89** [comment]
I'm experience this too but it looks random, can not reproduce it when I want to

**Comment by FabioAntunes** [comment]
I'm experiencing the same, I was just exploring the basic example and adding redux to it. Whenever I start the app it starts in a recompile loop until eventually stops, after a while I need to Sigterm the process and start again because it won't recompile anymore .

is there something I can do to help debugging this?

**Comment by ctrlplusb** [comment]
I've experienced similar in another tool I am building. Will share if I gain any insight into it.
