### ISSUE TITLE
Deploying to heroku causes mixed content error

### ISSUE THREAD

**Issue by meeoh** [jaredpalmer/razzle#354]
Specifically after I deploy I get this:
`Mixed Content: The page at 'https://whatever.herokuapp.com/' was loaded over HTTPS, but requested an insecure script 'http://localhost:46655/static/js/client.js'. This request has been blocked; the content must be served over HTTPS.`

My package.json looks like this: 
```
{
  "name": "my-razzle-app",
  "version": "0.1.0",
  "license": "MIT",
  "scripts": {
    "start": "razzle start",
    "build": "razzle build",
    "test": "razzle test --env=jsdom",
    "start:prod": "NODE_ENV=production node build/server.js",
    "heroku-postbuild": "npm run build"
  },
  "dependencies": {
    ...
  }
}
```

**Comment by marcelogdeandrade** [comment]
How did you fix it?

**Comment by guisteps** [comment]
How did you fix it? (2)

**Comment by meeoh** [comment]
I changed my package.json to this
```
    "scripts": {
        "dev": "razzle start",
        "build": "razzle build",
        "test": "razzle test --env=jsdom",
        "start": "NODE_ENV=production node build/server.js",
        "heroku-postbuild": "npm run build"
    },
```

**Comment by karan-karnad** [comment]
what is the solution here ?

**Comment by laurencefass** [comment]
subscribing.

**Comment by meeoh** [comment]
@karan-karnad @laurencefass The solution was to add the heroku-postbuild under scripts in package.json

**Comment by shivaaudam** [comment]
i added heroku-postbuild too but still the same error

**Comment by zikyfranky** [comment]
Dropping this Comment for future users who fall into this issue

Error is caused by trying to load an insecure script "HTTP" from a secured URL "HTTPS"

#Fix 1
One way to fix the issue will be to visit the insecure version of the site (i.e) http://whatever.herokuapp.com but this isn't a good fix cause your viewers won't know what the issue is which brings us to Fix 2

#Fix 2
Get the URL to determine what protocol the very instance is making use of
In PHP, i did this using this lines of code

    if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on'){ $protocol = "https://".$_SERVER['HTTP_HOST']; } else{ $protocol='http://'.$_SERVER['HTTP_HOST']; }

and then appending the protocol to what ever you are importing from your website

If the import is from an external website, just replace http in your `script` tag or `style` tag with `https`.

Hope this helps.

**Comment by amenalahassa** [comment]
For Laravel project, add it where ? please

**Comment by Dejan-Teofilovic** [comment]
You can just go for:
`'//myserverapp.herokuapp.com/'`
If you do want to write the protocol and still avoid mixed content, use:
`location.protocol + '//myserverapp.herokuapp.com/'`
