### ISSUE TITLE
`getInitialProps` for razzle?

### ISSUE THREAD

**Issue by paOol** [jaredpalmer/razzle#373]
next.js has 
```
 static async getInitialProps() { 
  }
```

this basically does a server-side request and allows you to use that data on render versus 

-page loads
-ajax request made when component mounts

one of the disadvantages of the 2nd approach is that you don't get SEO with it.

Is there are similar method for razzle?

**Comment by jaredpalmer** [comment]
Razzle is agnostic about how you fetch data. This can certainly be accomplished though

**Comment by NickCis** [comment]
@paOol In order to get a next.js like `getInitialProps` you could use [React data ssr](https://www.npmjs.com/package/react-data-ssr) (or redux version [redux data ssr](https://www.npmjs.com/package/redux-data-ssr)).

For a complete example of how to achieve it (using razzle, react, redux, redux data ssr, react router config, etc), you can check [this example](https://github.com/NickCis/radioactive-bird)

**Comment by jaredpalmer** [comment]
stay tuned i have something i am working on.

**Comment by AndyArcherKG** [comment]
@jaredpalmer is this still in on the Radar and or completed?
Working with a single react page (no routing) which has several Async calls to make before first load.

**Comment by jaredpalmer** [comment]
After.js.

**Comment by pirey** [comment]
just want to add the link to the mentioned After.js repo.
https://github.com/jaredpalmer/after.js
