### ISSUE TITLE
Source-maps are empty production build

### ISSUE THREAD

**Issue by FabioAntunes** [jaredpalmer/razzle#463]
I was trying to use source-map-explorer on my .maps and I was getting a weird error, it turns out the source maps are almost empty.

Might be related to #290

@stereobooster reported the same problem on that issue, two days ago

**Comment by b-m-f** [comment]
Could you try this one https://github.com/bananenmannfrau/razzle/tree/source-maps-prod-fix ?

If that works Id open a PR if @jaredpalmer thinks this should be included. Might not be that everyone wants to have sourcemaps in prod. 

Otherwise you could overwrite the webpack config with the change that I did there. Just check out https://github.com/bananenmannfrau/razzle/commit/dc4646118627c1b909e8112ff29372a3a0d77f94 for what exactly is added.   
[This](https://webpack.js.org/configuration/devtool/#devtool) is the documentation for the change

**Comment by FabioAntunes** [comment]
Yep extending the config works, would probably be nice to have a better documentation on the readme

**Comment by Metnew** [comment]
Have the same problem, `cheap-module-source-map` isn't for production usage according to webpack docs.

**Comment by jpetitcolas** [comment]
@b-m-f: your fix works fine for me. As a sidenote, here is the `razzle.config.js` file to override the sourcemap config:

```js
module.exports = {
    modify: (config, { target, dev }, webpack) => ({
        ...config,
        devtool: dev ? 'cheap-module-source-map' : 'sourcemap',
    }),
};
```

I'm opening a pull request.

**Comment by capaj** [comment]
@jpetitcolas thanks so much for this answer. It just saved me hours of webpack config tweaking and bashing my head against the table.
