### ISSUE TITLE
Add React-helmet-async example

### ISSUE THREAD

**Issue by jaredpalmer** [jaredpalmer/razzle#483]

**Comment by DevanB** [comment]
@jaredpalmer Not sure this would be solved by async/suspense (because I'm still having issues wrapping my head around Suspense in general 😞 ), but I have noticed something in my site (in production).

I'm setting the `<title>` in the server.js, and using react-helmet on a per-page basis to change that title and description. When I navigate away from the home page, via a nav link, then press Back in the browser the title tag is not reverting to the home page's titles. I believe this is because the home page doesn't have react-helmet set meta-data, and I'm incorrectly assuming that it should default back to the `server.js` included tags when no tags are set within the component. 

Is this a correct assumption? Does an async example solve this in any way?

**Comment by jaredpalmer** [comment]
You are correct. Suspense SSR isn't done yet, but it could solve problems like this. Furthermore, title tags really only matter for SEO (so first render only).

**Comment by DevanB** [comment]
Ahh, great to know. I'm being told by our SEO/analytics person that `title` tags matter on each page since the crawler would be crawling each page and expecting a different title per page (same with description, canonical links, and hreflang tags, apparently).

Thanks for the information! 😄

**Comment by snow-summer** [comment]
Titles matter for more than SEO :) Not only for UX/UI but if a visitor bookmarks a page they will expect the title to be correct for the page they are bookmarking.

**Comment by greatwitenorth** [comment]
Saw this was closed and was just wondering what the possibility was of seeing an example of React-helmet-async and razzle working together?

**Comment by lucasreppewelander** [comment]
as regular react-helmet doesn't work if you use `renderToNodeStream` I found an issue about it at [react-helmet](https://github.com/nfl/react-helmet/issues/322#issuecomment-366170439) but I found that the example with `renderToNodeStream` on react-helmet-async is too opinionated against apollo..

anyone with more experience in this that could assist how to pipe in the data from the stream?
