### ISSUE TITLE
Add PROTOCOL (http, https) to .env

### ISSUE THREAD

**Issue by dvdmgl** [jaredpalmer/razzle#503]
http is hardcoded, allow to be a choice through .env

`process.env.PROTOCOL`: default `http`

**Comment by vladp** [comment]
sorry, if this obvious. but how do you make my environment service HTTPS (I have the SSL certificates already generated)?



**Update:**  I just modified index.js directly (created by create-razzle-app ), and spawned https server, rather than http.  hope that was the right way of doing it.

**Comment by jmca** [comment]
This should be reopened.

**Comment by laurencefass** [comment]
Please repoen as razzle is currently broken by default for https sites.

**Comment by anthony0030** [comment]
I am also interested in HTTPS.

**Comment by laurencefass** [comment]
https://www.npmjs.com/package/razzle-plugin-proxy.

you can proxy https through nginx for multiple rather than configure individual applications.

install the proxy and follow some file changes... replace **${port...}** with your preferred port and domain .com with your reverse proxy server root location.

```
**.env**

# dev mode with path
PUBLIC_PATH='https://domain.com/razzle-dev/'
CLIENT_PUBLIC_PATH='https://domain.com/razzle-dev/webpack/'
PORT=${port}

# production mode with path (run with start:prod)
# PUBLIC_PATH=https://domain.com/razzle-prod
# PORT=${port+2}
```

**need to set the BrowserRouter basename client.js so you can use '/' as root everywhere else**

```
hydrate(
  <BrowserRouter basename="/razzle-dev">
    <App />
  </BrowserRouter>,
  document.getElementById('root')
);
```

configure **nginx locations**

```
    # razzle.js locations
    location ^~ /razzle-dev/webpack/sockjs-node/ { 
        proxy_pass http://0.0.0.0:${port+1}/sockjs-node/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }     
    location ^~ /razzle-dev/webpack/ {
        proxy_pass http://0.0.0.0:${port+1}/;
        proxy_http_version 1.1;
        as above
    }      	
    location /razzle-dev/ {
        proxy_pass http://0.0.0.0:${port}/;
        as above
    }      	
    location /razzle-prod/ {
        proxy_pass http://0.0.0.0:${port+2}/;
        as above
    }      
```

**Comment by SuperIRis** [comment]
I tried to make this work by editing index.js as @vladp pointed out, but now I'm getting a SockJS error (ERR_SSL_PROTOCOL_ERROR, then the warning that triggers when the socket closes), it seems that the content is not being served by https in the server side for static assets? Not sure exactly what is going on, any experience on something like this?

**Comment by SuperIRis** [comment]
Just in case it is useful for anyone else, I got it working by adding the files for my cert inside devServer.https config inside razzle.config (same way as in index.js), and overwriting the client public path by adding https (`CLIENT_PUBLIC_PATH=https://localhost:3001/`) since protocol is hardcoded in createConfig.
