### ISSUE TITLE
I have environment variable setup on heroku, but the applications shown only the environment variables that was specified from .env

### ISSUE THREAD

**Issue by iamrommel** [jaredpalmer/razzle#514]
I got .env files, it builds fine, but i also have setup the environment variables from heroku settings, 

My application can only see the variables that was define from env, and does not show the variables that i defined from heroku, something that webpack define plugin overrides all webconfig so it will show only razzle config.

Is there a way we cannot override the environment variables that was define in other place?

**Comment by meeoh** [comment]
If I'm understanding this right, your application thats running on heroku is reading vars from a .env file but you want the vars you defined in heroku to show up instead? I'm pretty sure thats not how you're supposed to use .env. I think the point of a .env file is that you DONT commit it to your repo, and in order to define the environment variables in heroku, you just use their config vars section under settings. Also, remember that your keys have to be prefixed by RAZZLE_ or else they wont be picked up, e.g
![image](https://user-images.githubusercontent.com/5509365/36599043-15cb8b06-187c-11e8-9eb2-059489377326.png)

**Comment by iamrommel** [comment]
Yeah i did that very long time, but i guess this webpack.definePlugin overrides the process.env and does not get values from heroku. it should merge the value not over-write it.

![image](https://user-images.githubusercontent.com/177265/36625313-202441e2-1958-11e8-9479-4def85b1de5d.png)

here is the value of my process.env,  after some console.log on the app

![image](https://user-images.githubusercontent.com/177265/36625326-6e25be16-1958-11e8-9228-dfed2cf345f3.png)
here is the keys of my environment variables defined in my workspace. as you can see all of them are missing from the process.env that i used fro previous image

![image](https://user-images.githubusercontent.com/177265/36625358-f62df36e-1958-11e8-97ed-62f1081aad6e.png)
This line of code from razzle overrides the existing value of my process.env, that it why it was just showing few. 

That is why the only workaround for me, is to add a new env.production (not commited to my repo), with all my configs define on that file, then do razzle build, and deploy the created files on build. With that process.env will have values that came from env.production. BUT I DONT WANT THAT, i want to get it from heroku config (or used my captainduckduck environment variables)
