### ISSUE TITLE
serving a new file without re-compiling?

### ISSUE THREAD

**Issue by paOol** [jaredpalmer/razzle#517]
I generate my sitemap.xml file in my app.

however, when its being run in production, the old stale sitemap is shown when I visit example.com/sitemap.xml

If I check the contents on the server, it is indeed overwritten with the fresh sitemap.

to get it to serve properly, I have to shut down the node server, and re-build. 

Obviously not ideal. Is there a better method of serving the new file w/o restarting the server?

**Comment by paOol** [comment]
my solution was to edit nginx 
```
  location ~ ^/(sitemap.xml) {
        root /srv/mywebsite/public;
    }
```

however, I am also trying to cache assets now and they are getting a 404 error when trying 

```
  location ~ ^/(images/|img/|javascript/|js/|css/|stylesheets/|flash/|media/|static/|robots.txt|humans.txt) {

         root /srv/mywebsite/build;
          access_log off;
          expires max;
        }
```

i've also tried just `/srv/mywebsite/` as well as `/srv/mywebsite/static`.
neither work.

has anyone had success caching their static assets with razzle?

**Comment by ComputerCarl** [comment]
You've probably got this already figured out since it's been a while, but;
I was having 404 errors also and I thought it was Apache.
However, if you build the project on your dev machine, you can launch it with `node build/server.js` and see if it's a proxy problem or not.
I also try to run it remotely using the port (if it's not blocked on the remote server) to bypass the change for a proxy configuration error.
In Apache, I had to change the configuration like so;
```
ProxyPassMatch ^/(.*) http://127.0.0.1:3007/$1
ProxyPassReverse ^/ http://127.0.0.1:3007/(.*)
```
The build folder was a little confusing to me because it contained some of the same files in `/static` and `/public`. If I remember correctly, the file should go into the public folder, and I had some problems with a dynamically-generated `sitemap.xml` because of this and maybe also a permissions error.
