### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by gregmartyn** [jaredpalmer/razzle#554]
I've run into a couple issues when running Razzle in a Docker container, mostly because of 127.0.0.1 assumptions.

- [x] The --inspect parameter to razzle start, which sets INSPECT_ENABLED, doesn't pass through the IP address. E.g. --inspect=0.0.0.0:9229. By default, inspect uses 127.0.0.1, which I can't port forward from the host to port 9229 inside the container.

- [ ] There's no way to tell the client which hostname to connect to. localhost:81 is assumed. PR here: #530 

- [x] Environment variables aren't being treated as variables. Docker builds static images that expect to be deployed in different environments and controlled by environment variables. #528

**Comment by adamjv90** [comment]
I too am running into a similar issue using docker-compose. I would like my client side build to contain the values of ENV vars at build time. But come runtime id like my server to pull from the runtimes ENV vars, basically as stated here https://github.com/jaredpalmer/razzle/issues/528#issuecomment-372998123  . Reason behind this is because i am docker-composing a nginx reverse proxy which sits in front of my api and razzle application. On the client i need my application to query the exposed reverse proxies port. However on the server i need my application to query my api service directly as described here https://docs.docker.com/compose/networking/

**Comment by ikappas** [comment]
@gregmartyn @adamjv90 have a look at https://github.com/jaredpalmer/razzle/issues/528#issuecomment-386563055

**Comment by jwickens** [comment]
An issue im running into right now is that RAZZLE_PUBLIC_DIR by default injects the full path from the build machine, which for CI performance reasons is completely different from the runtime machine where i copy the built assets.

**Comment by tesharp** [comment]
@jwickens I have the same problem and ended up with trying to avoid using RAZZLE_PUBLIC_DIR unless running in local dev mode. Using node module is-docker I run following:

```javascript
const isDocker = require('is-docker');
const env = require('get-env');

const staticPath = env === 'dev' && !isDocker() ? process.env.RAZZLE_PUBLIC_DIR : path.join(__dirname, '../build/public');

server.use(express.static(staticPath));
```

Not ideal, but at least it works. Runs fine both in local dev mode and inside docker.

**Comment by butterybread** [comment]
@jwickens If you know what the location of your public dir will be at runtime, use that to overwrite the RAZZLE_PUBLIC_DIR env var when running the build command and it should work.
