### ISSUE TITLE
what are the difference b/w nuxtjs and razzle?

### ISSUE THREAD

**Issue by Nisthar** [jaredpalmer/razzle#583]
I am currently using nuxtjs. what are the difference b/w nuxtjs and razzle?

**Comment by noeljackson** [comment]
nuxt is for just Vue apps, it's a lot like Next.js, but Next has since started to support  a lot more frameworks. Razzle works with a lot more frameworks than Vue or React (Elm, Reason, etc). Razzle is just an engine to power your app, abstracting away the complexity and tedious setup, and gives you a lot more flexibility for how your app works, without the headache.
