### ISSUE TITLE
Render problem with IE11 :question

### ISSUE THREAD

**Issue by ekbel** [jaredpalmer/razzle#599]
i use razzle to build my React application but it doesn't render correctly on IE 11 , (button , sidebar , popup ..)
what configuration i must use ? 
or any babel module can resolve that issue ?

**Comment by lesreaper** [comment]
Same issue. I get ```webpackJsonp is undefined``` in the Dev tools, which is something with loading order I believe. Still troubleshooting myself.

**Comment by lesreaper** [comment]
I ended up upgrading to the latest razzle (2.2.0) and webpack (4.10+) in my package.json, deleting my node_modules, doing a `yarn install` instead of `npm install`, and then adjusted my webpack to switch from ExtractTextPlugin to MiniCssExtractPlugin. Now using Yarn instead of NPM for everything. Had to rework the webpack config with the upgrade as well a little, but nothing major. After that, everything is good in IE11.

**Comment by SaraVieira** [comment]
@jaredpalmer I think this can also closed
