### ISSUE TITLE
Flashes of no CSS or unstyled webpage on load

### ISSUE THREAD

**Issue by iamrommel** [jaredpalmer/razzle#636]
Whenever i load the page, there is a quick flash of un-styled document, and then suddenly (after 1 second) it will load the correct style. I did a quick look for the main html that is being rendered dont have that assests.client.css

What is want is no flashes of unstyled webpage just like the old times. Or maybe im doing wrong with my code (see teh attached image)

![image](https://user-images.githubusercontent.com/177265/40884962-309a2ed8-6750-11e8-8ea1-2bc24513cae2.png)

**Comment by AndyArcherKG** [comment]
We have this issue to, are you lazy loading your pages? if so i think this is where the problem lies. 
A `feature` of webpack4/mini-css-extract-plugin is to help with page load by only loading the css when its "needed". Even in the current razzle setup where they `chunk` it all into one thing. Webpack still sees this as a chunk rather than an actual bundle from what i can tell. As such it wont include it in the `assets.json` which is where that condition in your screenshot is looking at.
If you go into `build/assets.json` there you will only see your js file referenced but not your css file even though its one big file. 

Steps to reproduce the error: 

1) have a lazy loaded route page with styles included (that you want ssr'ed)
2) run the build
3) check `build/assets.json` it doesnt show the css file.
4) `npm run start:prod` and check the browser you'll see the FOUC.

**Comment by david-potgieter** [comment]
Came here with same issue, solution here: https://github.com/jaredpalmer/razzle/issues/307

FOUC only during dev...

**Comment by ellis-oracle-jet** [comment]
i met the same obstacle and came up with the solution https://stylesheets.space/questions/what-is-the-maximum-length-a-webpage-can-reach
