### ISSUE TITLE
How to preload content?

### ISSUE THREAD

**Issue by markolofsen** [jaredpalmer/razzle#681]
Example [https://github.com/markolofsen/razzle-material](https://github.com/markolofsen/razzle-material)

How to preload content (with ajax) for SSR before load the page?

**Comment by rayandrew** [comment]
you might want to look for redux example here:

https://github.com/jaredpalmer/razzle/blob/master/examples/with-redux/src/server/index.js#L19

It preloads counter before render the page itself.

You can try combining it with matchPath function in react-router-dom so that every router has their fetch data logic

**Comment by liamwang** [comment]
Step 1:

[https://github.com/liamwang/react-starter/blob/ssr/src/server.js#L55-L59](https://github.com/liamwang/react-starter/blob/ssr/src/server.js#L55-L59)

Step 2:

[https://github.com/liamwang/react-starter/blob/ssr/src/pages/Home.js#L8-L10](https://github.com/liamwang/react-starter/blob/ssr/src/pages/Home.js#L8-L10)

**Comment by markolofsen** [comment]
@rayandrews — Thanks
@liamwang  — Thanks
