### ISSUE TITLE
Keep the default development Host (localhost) unopinionated or configurable via razzle.config.js

### ISSUE THREAD

**Issue by madiodio** [jaredpalmer/razzle#713]
Hi, first of all would like to say that razzle is a great tool.
The readme says about the `publicPath` option in development that it is
> explicitly set to localhost:3001 (and not / like many other setups do).

However, by doing this the development server url becomes not so much configurable and we end up encountering issues like these #263, #710, #610. I'm aware that you can change the default host by adding `HOST= 192.168.1.2` to the `.env` file or by prepending `HOST=192.168.1.2` to the `razzle start` as described [here](#710) as a solution. But what if the IP changes everytime? What if you use a service like [ngrok](https://ngrok.com/) which generates a url some unique ids every time you start the server? Then you have to change the HOST almost everytime or it would just break.
Imo, this should be either unopinionated and just stay `/`or make it configurable.

**Comment by jaredpalmer** [comment]
Yeah this would be good to figure out. However, it needs an explicit host because Razzle needs 2 ports during development mode. Using just a slash would point to the wrong place.

**Comment by madiodio** [comment]
Got it, can't disagree this would be hard to get right because of the 2 ports. Can you elaborate a bit why there is a need to set up 2 ports? Would it break everything (eg. needs a rewrite) if there was just 1 port?

**Comment by jaredpalmer** [comment]
Razzle would need to be runtime dependency or middleware, right now it’s build time. One port is for your server another port is for the webpack client bundle.

**Comment by gregmartyn** [comment]
This was my attempt at a fix: https://github.com/jaredpalmer/razzle/pull/740

FWIW, I've been using that patch for a couple months now and haven't had any trouble.

**Comment by jmpowen** [comment]
Just wondering if host has ever been made configurable? I ask because I am trying to create a docker container to run my razzle app. This requires me using the docker-machine ip 192.168.99.100

**Comment by gregmartyn** [comment]
Mostly. There are still some issues.

#740 CLIENT_PUBLIC_PATH was merged, and Razzle v2 introduced Runtime environment variables, which both helped a lot.

There's a new issue in v3 with the socket that the client is trying to connect to. It's using localhost instead of CLIENT_PUBLIC_PATH.

https://github.com/jaredpalmer/razzle/pull/581 was never accepted (v3 version https://github.com/jaredpalmer/razzle/pull/1020) which I think would go a long way toward making these issues go away. It introduces a client port var instead of calculating which port the client should connect to in different places.
