### ISSUE TITLE
Elm example Webpack config broken

### ISSUE THREAD

**Issue by manuca** [jaredpalmer/razzle#724]
Hi I noticed this error today after scaffolding a new Elm project using Razzle.

Steps to reproduce:
  - `create-razzle-app -e with-elm sample-project`
  - `cd sample-project`
  - `yarn start`

Then I get:

```
yarn run v1.7.0
$ razzle start
 WAIT  Compiling...

TypeError: Cannot read property 'push' of undefined
    at modify (/Users/manu/laburo/lafranja/v3/sample-project/razzle.config.js:7:39)
    at module.exports (/Users/manu/laburo/lafranja/v3/sample-project/node_modules/razzle/config/createConfig.js:613:14)
    at main (/Users/manu/laburo/lafranja/v3/sample-project/node_modules/razzle/scripts/start.js:47:22)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
✨  Done in 1.79s.
```

I believe this is something related to a breaking change in Webpack's config format. Internally this seems to be Webpack 4.6.

Thanks

**Comment by WolfDan** [comment]
Hey @manuca !

It's been a while since I have done the Elm example, right now I moved to ReasonML and have been a while since I used Elm and Razzle, but checking out the source code I think you need to do this to make it work correctly 

- Run `yarn add razzle-plugin-elm --dev` 
- Change all code in `razzle.config.js` for

```javascript
// razzle.config.js

module.exports = {
  plugins: ['elm'],
};
```

Reference: https://github.com/jaredpalmer/razzle/tree/master/packages/razzle-plugin-elm

Tell me how that goes ^^/

PD: _Que genial conocer a otro programador de lenguajes funcionales de habla hispana, saludos!_

**Comment by manuca** [comment]
Cool, thanks man I'll check this out again but it's weird it is failing while using the example that comes with Razzle.

PD: _@WolfDan muchas gracias, de donde eres?_

**Comment by WolfDan** [comment]
Since I did the PR the example haven't been updated, and apparently the razzle config api changed after al lthis time, so I think the example must be updated for the actual version of Razzle that I guess is the solution I gave to you, but right now I don't have any setup to test that ^^'

PD: @manuca , de Colombia ^^ y vos?

**Comment by manuca** [comment]
👍 @WolfDan Argentina
